MYSQL_ROOT_PASSWORD: "{{ (lookup('amazon.aws.aws_secret', 'roboshop/dev/mysql_root_password', region='us-east-1') | from_json).MYSQL_ROOT_PASSWORD }}"

# # Source - https://stackoverflow.com/a/71960227
# Posted by β.εηοιτ.βε, modified by community. See post 'Timeline' for change history
# Retrieved 2026-02-22, License - CC BY-SA 4.0

# secret: >-
#   {{ 
#     (lookup(
#       'amazon.aws.aws_secret', 
#       'my/awesome/secret', 
#       region='eu-west-2'
#     ) | from_json).password 
#   }}

#MYSQL_ROOT_PASSWORD: "{{ lookup('amazon.aws.aws_ssm', '/roboshop/dev/mysql_root_password', region='us-east-1', decrypt=False ) }}"