$ANSIBLE_VAULT;1.1;AES256
37393831623862633534343332396265653338313838313439363461616438343662376130383463
3266313766306564333833303566323137306262313165300a623865346633376635623763363036
33386333626137626133326233633562636134373035303533636161303239306631363833346636
6638303532343735660a363835653030646430663039623137396532343664303735346435346230
39633530316236373133376565356539376265323036303064626464653437306136636661356239
3532373466646334383361396331653138613232303166613064
