- name: message 1
  ansible.builtin.debug:
    msg: "hello from msg-1"

- name: message 2
  ansible.builtin.debug:
     msg: "hello from msg 2"

- name: message 3
  ansible.builtin.debug:
    msg: "hello from msg-3"         