- name: install maven and mysql
  ansible.builtin.dnf:
       name: "{{ item }}"
       state: present
    loop:
    - maven
    - mysql   

- name : install dependencies
  ansible.builtin.command: mvn clean package
  args:
      chdir: /app # ikkadki move iyyi ikkade commond run avutundhi

- name: rename zip file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
     chdir: /app                             # ikkadki move iyyi ikkade commond run avutundhi

- name: install dependencie
  ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
  loop:
    - cryptography                       # manam password istunam kada so vatiki e library
    - PyMySQL                            # ikkada mysql backgroud lo python ni hit chestundhi so dhaniki e library  